language: go
sudo: false
matrix:
  allow_failures:
  - os: windows
  - go: master
  include:
  - os: linux
    go: 1.12.x
    cache:
      directories:
      - "/home/travis/.cache/go-build"
  - os: linux
    go: master
  - os: osx
    go: 1.12.x
    cache:
      directories:
      - "/Users/travis/Library/Caches/go-build"
env:
  global:
    secure: QPkcX77j8QEqTwOYyLGItqvxYwE6Na5WaSZWjmhp48OlxYatWRHxJBwcFYSn1OWD5FMn+3oW39fHknReIxtrnhXMaNvI7x3/0gy4zujD/xZ2xAg7NsQ+l5buvEFO8/LEwwo0fp4knItFcBv8xH/ziJBJyXvgfMtj7Is4Q/pB1p6pWDdVy1vtAj3zH02bcqh1yXXS3HvcD8UhTszfU017gVNXDN1ow0rp1L3ainr3btrVK9izUxZfKvb7PlWJO1ogah7xNr/dIOJLsx2SfKgzKp+3H28L2WegtbzON74Op4jXvRywCwqjmUt/nwJ/Y9anunMNHT136h+ye4ziG1i/VdbWq0Q4PopQ8yYqinujG7SjfQio+wNCV2cwc2r/WjNBjbH0N9/Pflogq3RHvgy/9VtPif1tY+RrZCSntohoEZbYpVcFQFE1xDyf6xq/uLxVeEcCU33gqq7cKEfpcUgyCITa+yCPfBdtgkLBJ8h7Sew1j08D1kTKUW6g3D1epmwlCh/Z16oHG5VwSnCLGDjJy8wm/hQk1i/g7qeP7g24CfNzffzlFBCy88HhjzmrhUpcaTyfVVDf4h8wK6Zu/J3dHjHXQYwfiQRqpMa+2DYyjGgZhniccuh4GWolGZauDQdmO9SD4Ugyt9PEMk02i32ax3A4XE/Q6VNOam+qszviX3Q=
  matrix:
  - GO111MODULE=on
before_install:
  - go get -u github.com/client9/misspell/cmd/misspell
  - go get -u golang.org/x/lint/golint
  - go get github.com/fzipp/gocyclo
  - go get honnef.co/go/tools/cmd/staticcheck
  - go get golang.org/x/tools/cmd/cover
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install -y mingw; export PATH=/c/tools/mingw64/bin:"$PATH";fi
before_script:
  - GOFILES=$(find . -type f -name '*.go' | grep -v vendor)
script:
  # Just check gofmt on linux, it's the fastest builder
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then test -z $(gofmt -s -l $GOFILES); fi
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic
  - misspell -error -locale US $GOFILES
  - gocyclo -over 26 $GOFILES
  - golint -set_exit_status $GOFILES
  - staticcheck ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - make docker
before_deploy:
  - make dist
deploy:
  provider: releases
  api_key:
    secure: GxT+ZSBd2KK/NPqIlDQ/aDDXgUSpLa7VatmYe4MgHI3cE/nKPagMtxPUNG8i4m2qR1nSh5E+Iqg91lnI59lWYlCDKyFw5w328bHR4fuuzWo18AY0ENA4oXYaoqkwbmQ0GDkR/XW2W78SveMhsrhkMdyHIcg8Z4rRyCSnZRO1sYd7TB67ExNzEZezR+37j1ygzD2tem/l2na/ltCPKo6xlL5saAORYw5UKWwHWEpLtn2tc4xYUSqYWJ5Vmczypa6W9NNfBRVoFqywyytQjRDnXG1zOEQaBnxb6/GsE/o3CmSlMIyVtH3aco9M9PnnQ3J9AOm7ojgovoozUF2uEEpEYc99U1hWH++FBL5eVejnKka0mKZ6pkt/0li541M2yfT0tN8w/w44a14s10HNrygeQLn6F1ua4LkqgmbbWFeGZ1Fa5dppQGQkXGc5uyUj27UMPUR5eNPkEhz3Yu004zBLHym8TJIJv20+VQn3sW0cPlNLYVIYUDamwOyznaXKX+/u0ks+npcCpRYgEiAdK3fSYNk6L8ziDs8V61sJTSS6hN2Ny2ncz1s3hDX+iejmDZdon1VEvvcnWFwzNS14fUMKhzyus9ufCjdyFJqZTtqRICtvKEfUDIavm93HAKyUdDR5A2foShf/mIq+lyG6Eo6QK9RbiXHwoAB8tnxj0TB1bMw=
  on:
    tags: true
  file:
    - bin/ach-amd64.exe
    - bin/ach-darwin-amd64
    - bin/ach-linux-amd64
  skip_cleanup: true
after_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make release-push
